---
title: "My list of publications"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    toc-expand: true 
    toc-title: "Contents"
    fontize: 0.9rem
    css: styles.css
---

```{r, echo=FALSE}
library(fontawesome)
```

Here you can find abstracts and links to my publications.

If you can't access a publication please don't hesitate to contact me.

You can also find me on [GoogleScholar](https://scholar.google.de/citations?hl=es&user=uG2XdQcAAAAJ) and [ResearchGate](https://www.researchgate.net/profile/Miriam-Lerma).

My ORCID is [0000-0002-7632-9289](https://orcid.org/0000-0002-7632-9289).

# 2024

### 12. Variations in inter‐specific and sex‐related niche partitioning in pelagic boobies during their annual cycle

**Authors**: **Lerma M**, Dehnhard N, Castillo-Guerrero JA, Hernandez-Vazquez S, Voigt CC, Garthe S\
**Abstract** Animals that co-occur in a region (sympatry) may share the same environment (syntopy), and niche differentiation is expected among closely related species competing for resources. The masked booby (*Sula dactylatra*) and smaller congeneric red-footed booby (*Sula sula*) share breeding grounds. In addition to the inter-specific size difference, females of both species are also larger than the respective males (reversed sexual size dimorphism). Although both boobies consume similar prey, sometimes in mixed-species flocks, each species and sex may specialize in terms of their diet or foraging habitats. We examined inter- and intra-specific differences in isotopic values (δ13C and δ15N) in these pelagically feeding booby species during the incubation period at Clarion Island, Mexico, to quantify the degrees of inter- and intra-specific niche partitioning throughout the annual cycle. During incubation, both species preyed mainly on flyingfish and squid, but masked boobies had heavier food loads than red-footed boobies. There was no overlap in isotopic niches between masked and red-footed boobies during breeding (determined from whole blood), but there was slight overlap during the non-breeding period (determined from body feathers). Female masked boobies had a higher trophic position than conspecific males during breeding; however, no such pattern was detected in red-footed boobies. These results provide evidence of inter- and intra-specific niche partitioning in these tropical seabird species, particularly during the breeding period and in the more-dimorphic species. Our results suggest that these closely related species use different strategies to cope with the same tropical marine environment.\
**Read more:** [Link to publication](https://onlinelibrary.wiley.com/doi/10.1002/ece3.11255)

# 2023

### 11. Corticosterone levels, leukocyte profiles, and foraging and diving behaviours of Humboldt penguins during chick rearing in Northern Chile

**Authors**: **Lerma M**, Villavicencio CP, Luna N, Portflitt-Toro M, Serratosa J, Luna-Jorquera G, Garthe S, Quispe R\
**Abstract** Understanding the physiology of stress in wild animals is essential for the conservation of species subject to anthropogenic perturbations. Humboldt penguins (*Spheniscus humboldti*) are exposed to increasing anthropogenic impacts in their natural habitat. In this species, females are typically smaller and dive less deep than males. In related species, the more limited foraging habitat of females and their reduced resiliency due to their smaller size were associated with higher mortality. We hypothesise that potential sex-specific differences in the foraging behaviour of Humboldt penguins may also relate to differences in their physiological stress. Here, we studied sex-specific foraging and diving behaviours and variations in plasma corticosterone levels and leukocyte profiles of Humboldt penguins during the chick-rearing period in Northern Chile. We report no evidence of sex-related differences in most foraging parameters, except that males dived significantly deeper than females. We found that plasma corticosterone levels and leukocyte profiles showed no significant differences between the sexes. Furthermore, there was no clear relationship between an individual’s foraging behaviour and its plasma corticosterone level or leukocyte profile. In summary, we found no support for sex-related differences in physiological stress levels of Humboldt penguins, and no link between their foraging behaviour and their physiological stress. However, we acknowledge that our sample size is small and that more studies are needed. This study contributes with information on the physiological stress and foraging behaviours of Humboldt penguins in Northern Chile. This information can help to understand context-dependent differences in physiological parameters and foraging behaviours for the species.\
**Read more:** [Link to publication](https://www.tandfonline.com/doi/abs/10.1080/01584197.2022.2153699?journalCode=temu20)

### 10. Seabird morphology determines operational wind speeds, tolerable maxima, and responses to extremes

**Authors**: Nourani E, Kamran S, de Grissac S, Anderson D, Cole NC, Gremillet D, Lempidakis E, **Lerma M**, McKee JL, Pichegru :, Provost P, Rattenbourg NC, Ryan P, Santos CD, Schoombie S, Tatayah V, Weimerskirch H, Wikelski M, Shepard ELC\
**Abstract** Storms can cause widespread seabird stranding and wrecking, yet little is known about the maximum wind speeds that birds are able to tolerate or the conditions they avoid. We analyzed \>300,000 h of tracking data from 18 seabird species, including flapping and soaring fliers, to assess how flight morphology affects wind selectivity, both at fine scales (hourly movement steps) and across the breeding season. We found no general preference or avoidance of particular wind speeds within foraging tracks. This suggests seabird flight morphology is adapted to a “wind niche,” with higher wing loading being selected in windier environments. In support of this, wing loading was positively related to the median wind speeds on the breeding grounds, as well as the maximum wind speeds in which birds flew. Yet globally, the highest wind speeds occur in the tropics (in association with tropical cyclones) where birds are morphologically adapted to low median wind speeds. Tropical species must therefore show behavioral responses to extreme winds, including long-range avoidance of wind speeds that can be twice their operable maxima. By contrast, Procellariiformes flew in almost all wind speeds they encountered at a seasonal scale. Despite this, we describe a small number of cases where albatrosses avoided strong winds at close range, including by flying into the eye of the storm. Extreme winds appear to pose context-dependent risks to seabirds, and more information is needed on the factors that determine the hierarchy of risk, given the impact of global change on storm intensity.\
**Read more:** [Link to publication](https://www.sciencedirect.com/science/article/pii/S0960982223001379)

# 2022

### 9. Nutritional state variations in a tropical seabird throughout its breeding season

**Authors**: **Lerma M**, Dehnhard N, Castillo-Guerrero JA, Fernandez G\
**Abstract** Individual body condition is frequently used to explain differences in foraging and breeding ecology in seabirds. However, little is known about the covariations of body mass with the nutritional state of animals as measured through plasma metabolites and how these different measures vary between and within individuals during breeding. Here, we assessed intra-individual variations of plasma metabolites (triglycerides, cholesterol, protein, and ß-hydroxybutyrate concentrations) and in body mass of Blue-footed boobies (*Sula nebouxii*) throughout their breeding season 2011–2012 in Isla El Rancho, Mexico. We found breeding-stage and sex-specific variations in individuals’ plasma metabolite concentrations, but these did not mirror variations in body mass. Before egg-laying, females had higher triglycerides, cholesterol, and protein concentrations than males. In contrast, males used their nutritional reserves (higher ß-hydroxybutyrate concentrations) more than females during the breeding season (except for early chick-rearing). At the individual level, males gained weight during the breeding season, whereas females lost weight. We also found that between-individual differences in plasma metabolite concentrations and changes in body mass were not consistent throughout the breeding season, while individual body mass was significantly repeatable. This study contributes to a better understanding of seabird breeding ecology and physiology by showing that sex-specific breeding roles might highly influence the nutritional state. Similar patterns might occur in other seabird species, helping to explain why we can find stage- and sex-specific foraging behaviors even in monomorphic species.\
**Read more:** [Full publication](https://link.springer.com/article/10.1007/s00360-022-01456-3)

# 2020

### 8. Breeding stage, not sex, affects foraging characteristics in masked boobies at Rapa Nui

**Authors**: **Lerma M**, Dehnhard N, Luna-Jorquera G, Voigt CC, Garthe S\
**Abstract** Sexual segregation in foraging occurs in some species and populations of boobies (Sulidae), but it is not a general pattern. Sexual segregation in foraging may occur to avoid competition for food, and this competition may intensify during specific stages of breeding. We examined sexual segregation in foraging in relation to breeding stage in masked boobies *Sula dactylatra* at Rapa Nui by tracking simultaneously incubating and chick-rearing birds using GPS recorders (n = 18) and collected a total of 11 regurgitate samples. Stable isotope analyses (δ13C and δ15N) of whole blood samples were carried out in 20 birds. There were no differences in foraging trip parameters or diet between females and males. Both sexes traveled farther and for longer while incubating than while rearing chicks. Isotopic niches (δ13C and δ15N) overlapped to some degree among all groups at all times, but the lowest overlap between sexes occurred during incubation. While preying on ephemerally distributed flying fish, vertical or horizontal competition avoidance may be almost impossible, and thus females and males share their foraging grounds. Since birds were tracked simultaneously, shorter foraging trips of chick-rearing birds must be an effect of the constraints of provisioning the chick. Differences observed in δ15N and δ13C values between sexes may be caused by subtle differences in their foraging behaviors, or by differences in physiology linked to breeding. Our findings suggest that local oceanography and its inherent food distribution are determinants for sexual segregation in foraging patterns in masked boobies and possibly also other booby species.\
**Read more:** [Full publication](https://link.springer.com/article/10.1007/s00265-020-02921-1)

### 7. Foraging ranges of Humboldt penguins *Spheniscus humboldti* from Tilgo island: the critical need for protecting a unique marine habitat

**Authors**: Quispe R, **Lerma M**, Luna N, Portflitt-Toro M, Serratosa J, Luna-Jorquera\
**Abstract** The largest population of Humboldt Penguins resides in a fertile archipelago of the north-central coast of Chile, formed by eight islands in proximity to upwelling centers of the Humboldt Current System. However, five of these islands lack legal protection. Here, we report the results of breeding Humboldt Penguins tracked while foraging from Tilgo Island. The average and maximum foraging radii around the colony were 22 km and 43 km, respectively. Our data indicate that trip ranges overlap areas proposed for industrial projects. Because Humboldt Penguins are sentinels of local ecosystem health, this underscores the value of expanding conservation zones in this unique marine location.\
**Read more:** [Full publication](http://marineornithology.org/PDF/48_2/48_2_205-208.pdf)

### 6. Foraging ecology of a marine top predator in the Eastern Tropical Pacific over 3 years with different ENSO phases

**Authors**: **Lerma M**, Castillo-Guerrero JA Hernandez-Vazquez S, Garthe S\
**Abstract** The El Niño Southern Oscillation (ENSO) is a recurrent climatic pattern with important ecological consequences for seabirds due to its impacts on the abundance and distribution of food resources. We investigated the effects of ENSO phases on the foraging ecology of a marine top predator at Clarion Island in the Eastern Tropical Pacific using GPS and time-depth recorder data and regurgitates from incubating masked boobies (*Sula dactylatra*) during 3 consecutive years. Foraging locations were recorded in 2016 (El Niño, one female, three males), 2017 (neutral; six females, nine males), and 2018 (La Niña; eight females, ten males). Local sea surface temperature (SST) and chlorophyll-a concentration (CHL) within the birds’ foraging range were compared among the 3 years. Regurgitates were collected opportunistically from 25 and 31 incubating adults in 2017 and 2018, respectively. Average local CHL and SST were similar among years (mean SST 25 °C; mean CHL 0.10 and of 0.09 mg m−3 in January and March, respectively). Masked boobies travelled a maximum of 66 ± 34 km from the colony. The maximum trip duration was 7.7 ± 3.4 h and total distance travelled during a foraging trip was 164 ± 73 km, with no sex- or year-related differences. Masked boobies mainly caught flying fish, but their diet also included one squid and six other fish families. In contrast to previously reported changes in foraging ecology of seabirds, masked boobies at Clarion Island seemed to be unaffected during El Niño, because the local oceanography was relatively unperturbed by ENSO oscillations.\
**Read more:** [Full publication](https://doi.org/10.1007/s00227-020-03699-6)

### 5. Foraging ecology of masked boobies (*Sula dactylatra*) in the world’s largest ‘oceanic desert’

**Authors**: **Lerma M**, Serratosa J, Luna-Jorquera G, Garthe S\
**Abstract** The South Pacific Gyre has the most hyper-oligotrophic waters in the world and is considered the largest “oceanic desert.” Rapa Nui (Easter Island), located within the South Pacific Gyre, is a breeding ground for masked boobies (*Sula dactylatra*), which are seabirds with a foraging range that effectively confines them within the gyre. The foraging ecology of this species in the gyre was examined by attaching GPS and time-depth devices to chick-rearing adult birds (9 and 14 birds in 2016 and 2017, respectively) and by collecting regurgitates (18 and 15 samples in 2016 and 2017, respectively). In addition, the birds’ foraging ecology between years was compared. Masked boobies traveled in various directions, dived at unspecific locations, and explored areas \< 110 km from the colony. Local environmental conditions were not significantly different between years, and differences in foraging parameters (maximum foraging range, trip duration, and dive depth) were greater among individuals than between years. The foraging characteristics of masked boobies suggest that resources were ephemerally distributed around the colony, with similar abundances across years. Under these conditions, traveling to unspecific locations may increase the area covered and the probability of prey encounter. The spatial and temporal consistencies in environmental conditions explain the uniformity of foraging parameters between years. The ability of masked boobies to exploit ephemerally distributed resources in seascapes like Rapa Nui may help explain its pantropical distribution.\
**Read more:** [Full publication](https://link.springer.com/article/10.1007/s00227-020-03700-2)

### 4. Zinc concentrations in Blue-footed booby (*Sula nebouxii*) eggs, nestlings, and adults

**Authors**: **Lerma M**, Castillo-Guerrero JA, Garcia-Hernandez J, Fernandez G\
**Abstract** Zinc is essential for animal metabolism, but the variation in Zn concentrations within seabird populations has been seldom explored. We collected Blue-footed booby (*Sula nebouxii*) eggs during 2012 and 2013 and blood samples from nestlings and adults during 2011 and 2012 in Sinaloa, Mexico, to evaluate differences in Zn concentrations among years, ages, sexes, and breeding stages. Zinc concentrations in eggs ranged between 27.3 and 64.9 ppm (dry weight), whereas Zn levels in the blood of nestlings and adults ranged between 16.1 and 53.1 ppm (dry weight). Egg Zn concentrations did not differ due to developmental stage, although Zn concentrations were significantly higher in 2013 than in 2012. Nestling Zn concentrations differed between years and decreased gradually with age. Chicks had significantly higher Zn concentrations than those of adults. Once nestlings stopped growing, females presented higher Zn concentrations than males. Adult Zn concentrations were higher during the pre-laying period than during the other breeding stages. Our results suggest that growth, sex, and breeding stage affect blood Zn concentrations, which may be due to stage-specific requirements. When compared with those of other seabird species, the Zn concentrations reported here are intermediate, and we did not detect adverse effects on either nestlings or adults.\
**Read more:** [Full publication](https://doi.org/10.1016/j.seares.2020.101952)

# 2017

### 3. Non-Breeding Distribution, Abundance, and Roosting Habitat Use of the American Oystercatcher (*Haematopus palliatus frazari*) in Sinaloa, Mexico

**Authors**: **Lerma M**, Castillo-Guerrero JA, Palacios E\
**Abstract** The American Oystercatcher (*Haematopus palliatus frazari*) is federally listed as endangered in Mexico due to habitat loss and small population size. Recent surveys indicate that the State of Sinaloa supports about half of the breeding population in Mexico. However, no information is available about the non-breeding ecology in Mexico. To assess American Oystercatcher distribution, abundance, and roosting habitat use during the nonbreeding season (3 August 2014-23 January 2015), six bays were surveyed in Sinaloa. A total of 1,351 American Oystercatchers were detected using this area based on maximum count per roosting site at or near high tide. American Oystercatchers roosted in flocks of variable size (3–253 individuals per flock) with Bahía Santa María hosting the main roosting sites in Sinaloa. Mangrove islands and mudflats had larger numbers of individuals than expected relative to the availability of those habitats. The non-breeding Sinaloa population comprised approximately 45.0% of the total H. p. frazari population estimate (n = 3,000 individuals). Bahía Santa María represented 74.6% of the non-breeding population observed in Sinaloa. Thus, Sinaloa, and particularly Bahía Santa María, stand out as critical sites for the conservation of this subspecies. Hypothesized threats to American Oystercatchers were predators, livestock, and human activities.\
**Read more:** [Full Publication](https://doi.org/10.1675/063.040.sp111)

### 2. Lead, cadmium and mercury in the blood of the blue-footed booby (*Sula nebouxii*) from the coast of Sinaloa, Gulf of California, Mexico

**Authors**: **Lerma M**, Castillo-Guerrero JA, Ruelas-Inzunza J, Fernandez, G\
**Abstract** We used blood samples of the Blue-footed Booby, considering sex (female and male) and age-class (adult and chick) of individuals at different breeding stages during two breeding seasons (2010–2011 and 2011–2012) in Isla El Rancho, Sinaloa, to determine lead, cadmium, and mercury concentrations. Lead and cadmium concentrations were below our detection limit (0.05 and 0.36 ppm, respectively). A higher concentration of mercury was found in early stages of breeding, likely related to changes in mercury environmental availability. Mercury concentrations in adults did not relate with their breeding output. Males and adults had higher mercury concentration than females and chicks. We provide information of temporal, sex and age-related variations in the concentrations of mercury in blood of the Blue-footed Booby.\
**Read more:** [Full Publication](https://doi.org/10.1016/j.marpolbul.2016.06.049)

# 2016

### 1. Environmentally-mediated flexible foraging strategies in Brown Boobies in the Gulf of California

**Authors**: Castillo-Guerrero JA, **Lerma M**, Mellink E, Suazo-Guillén E, Peñaloza-Padilla EA\
**Abstract** The Brown Booby *Sula leucogaster* is a seabird with a pantropical distribution across a wide variety of oceanic environments. Sexual size dimorphism in Brown Boobies has been proposed as an explanation for intersexual differences in foraging, but results have been inconsistent. We investigated whether there is context-dependent foraging behaviour driven by local environmental conditions. In this study, we evaluated (1) inter-sex differences in foraging behaviour (by capillary tubes, temperature and depth recorders, and diet) at two colonies in the Gulf of California: Isla San Jorge (ISJ) and Farallón de San Ignacio (FSI) and, (2) intercolonial and interannual differences in foraging behaviour, and (at ISJ) their relationship with local-scale environmental variation, using 5-day composite images of sea surface temperature (SST) and primary productivity (PP) as proxies. Inter-sex differences were few and inconsistent between years, and smaller than overall differences between years and localities. At ISJ, Brown Boobies included more prey species in their diet (27 vs. 19 spp.) and dove shallower (2.3 vs. 3.14 m) than at FSI. At ISJ, Brown Boobies exhibited adjustments in diving depth and prey size as a function of environmental variation: shallower plunge dives and smaller prey items were related with lower SST and higher PP values, whereas deeper dives and larger prey items were related with higher SST and lower PP values. Our results confirmed that the Brown Booby is highly plastic in its foraging ecology, which explains its ability to live in places with large-scale environmental variation (intercolony and interannual), such as tropical areas worldwide.\
**Read more:** [Full Publication](https://doi.org/10.5253/arde.v104i1.a3)
